defmodule AocTest.Day11Test do
  use ExUnit.Case

  alias Days.Day11

  test "part_one/1 works as expected" do
    assert Day11.part_one("""
           ...#......
           .......#..
           #.........
           ..........
           ......#...
           .#........
           .........#
           ..........
           .......#..
           #...#.....
           """) == 374
  end

  test "part_two/1 works as expected" do
    assert Day11.part_two(
             """
             ...#......
             .......#..
             #.........
             ..........
             ......#...
             .#........
             .........#
             ..........
             .......#..
             #...#.....
             """,
             10
           ) == 1030

    assert Day11.part_two(
             """
             ...#......
             .......#..
             #.........
             ..........
             ......#...
             .#........
             .........#
             ..........
             .......#..
             #...#.....
             """,
             100
           ) == 8410
  end
end
