import day
import days/day7

const input = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."

pub fn part_one_test() {
  assert day7.part_one(input) == day.IntResult(21)
}

pub fn part_two_test() {
  assert day7.part_two(input) == day.IntResult(40)
}
