mod day1;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;
mod day18;
mod day19;
mod day2;
mod day20;
mod day21;
mod day3;
mod day4;
mod day5;
mod day6;
mod day7;
mod day8;
mod day9;

fn main() {
    day21::dirac(false);
    day20::trench_map(true);
    day19::beacons_n_scanners(true);
    day18::snailfish(true);
    day17::trick_shot(true);
    day16::decoder(true);
    day15::chitons(true);
    day14::polymerization(true);
    day13::origami(true);
    day12::navigate(true);
    day11::octopus(true);
    day10::check_syntax(true);
    day9::smoke_basin(true);
    day8::displays(true);
    day7::crab_move(true);
    day6::lanternfish(true);
    day5::vents(true);
    day4::bingo(true);
    day3::diagnostics(true);
    day2::steer(true);
    day1::run_counts(true);
}
