require_relative "../../../lib/aoc/days/day8"

RSpec.describe Aoc::Day::Day8 do
  include Aoc

  input = "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............"
  day = Aoc::Day::Day8.new(input)

  it "solves part 1 correctly" do
    expect(day.part1).to equal(14)
  end

  it "solves part 2 correctly" do
    expect(day.part2).to equal(34)
  end
end
